language: java
install: true
before_script:
  - |
    if [ "$TRAVIS_TAG" != "" ]; then
      PHASES="install site"
    elif [ "$TRAVIS_PULL_REQUEST" != "false" ]; then
      PHASES="verify"
    else
      PHASES="deploy"
    fi
script: mvn -s config/settings.ci.xml $PHASES -PrunITs
after_success: mvn test jacoco:report coveralls:report -pl :bowman-client-with-http-caching
deploy:
  provider: pages
  local-dir: client/target/generated-docs
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    all_branches: true
    tags: true